### PR TITLE
Ability to copy a course with learning objectives

### LINKED ISSUE #4326: Learning objectives should be copied when copying a course with learning objectives turned on
### Expected Behavior
* When copying a course with learning objectives enabled, the learning objectives in the course should be copied over to the new course, along with any learning objective levels and linked assignments.

### Actual Behavior
* Currently, copying a course with learning objectives does not copy over the learning objectives in the course.

### Steps to reproduce
* As an admin, copy a course with learning objectives
* Visit the learning objectives page (i.e. /learning_objectives/objectives). The learning objectives from the original course are not listed in the current copy of the course.

### PR DESCRIPTION
**Pull request by adishy**
### Status
**IN DEVELOPMENT**

### Description
* Copying a course with learning objectives as an admin should result in the copied course having learning objectives from the original course with any linked assignments copied over as well.
* Currently, the learning objectives model does not have a `copy` helper for ModelCopier to perform the copying. 
* Now, a `copy` helper has been added to the learning objectives model and linked models
* Note:
  * This implementation does not account for the associations of students and grades in a course with learning objectives (i.e. learning objective observed outcomes, learning objective cumulative outcomes) and will not copy these associations in a course correctly. Due to this the "Copy + Students" option will not be displayed for a course with learning objectives in the options dropdown, in the overview page for courses (i.e. /courses/overview).

### Migrations
NO

### Steps to Test or Reproduce
1. As an admin copy a course with learning objectives.
2. The resulting copy should have the learning objectives from the original course along with any linked assignments in the original course.

### Impacted Areas in Application
* Learning Objective model (models/learning_objective.rb) and associated models 

======================
Closes #4326

### CODE REVIEW

**Comment by adishy** [comment]
image
Gradecraft Databse Relations Overview

File: app/models/learning_objective.rb [hunk 1]
```diff
@@ -119,6 +120,32 @@ def check_unlockables(student)
...
+      associations: [:levels],
+      options: { lookups: [:course, :category, :assignments],
+                 overrides: [-> (copy) { copy_category(copy, lookup_store) }, 
+                             -> (copy) { copy_assignment_links(copy, lookup_store) }] }
+    )
+  end
+
+  def copy_category(copy, lookup_store)
+    if copy.category.present?
+      equivalent_category_id_in_copied_course = lookup_store.lookup(:learning_objective_categories, self.category.id)
```
Comment (ebarroso7) [inline app/models/learning_objective.rb]: Great name! `equivalent_category_id_in_copied_course` 😎
