### PR TITLE
1740 Nil Changeset bug

### LINKED ISSUE #1740: Nil changeset bug
https://rollbar.com/gradecraft/gradecraft-development/items/1482/?person_page=0&#traceback

### PR DESCRIPTION
**Pull request by jwright**
A bug occurred on production for https://rollbar.com/gradecraft/gradecraft-development/items/1482/?person_page=0&#traceback.

This is a result of merging histories where the destination changeset does not exist.

This adds a check to the `#merge` operation on `HistoryFilter` to ensure that the destination exists before merging in the changeset.

Fixes #1740

### CODE REVIEW

File: app/models/history_filter.rb [hunk 1]
```diff
@@ -48,7 +48,9 @@ def merge(options)
 
     from_versions.each_with_index do |history_item, index|
       history_item.changeset.each_pair do |key, value|
-        if !["created_at", "updated_at"].include?(key) && value.is_a?(Array)
+        if !["created_at", "updated_at"].include?(key) &&
+            value.is_a?(Array) &&
+            to_versions.size > index
```
Comment (zazaian) [inline app/models/history_filter.rb]: This all looks good to me :+1: Out of curiosity what do the `to_versions` and `from_versions` methods reference here?

Comment (jwright) [inline app/models/history_filter.rb]: The `from_versions` is the `Version` history (which contains `changesets`) for the "from" class and `to_versions` is the history for the "to" class.
