### PR TITLE
2742 submission constraint fixes

### LINKED ISSUE #2742: Constraint Prevents Multiple Group Submissions
### Expected Behavior

We should be able to create many group submissions for a given assignment.

### Actual Behavior

A recently added constraint prohibits the creation of more than one submission per assignment and student. Current functionality is that one submission is created per group. A group submission is expected to have `student_id = nil`, therefore this validation will fail.

### Steps to reproduce

On a group assignment, create and submit a submission. Then try to create and submit another submission for the same assignment.

### PR DESCRIPTION
**Pull request by jonathoy**
### Status
Ready

### Description
This PR addresses a few issues that were discovered with a newly added `Submission` constraint. This should also fix the failing specs on master.

The constraint limited submissions to being one per assignment and student. However, the default behavior for the ActiveRecord constraint was to validate against `nil` values. This prevented multiple group submissions from being created, since a group submission is defined as being a `Submission` with a `group_id` but no `student_id`.

Additional changes were also made to the database as well as the `Submission` model to ensure that no more than one group submission can exist per assignment.

Finally, there is a newly added ActiveRecord constraint that dictates that a `Submission` is valid if it has either a non-nil value for `student_id` or `group_id`, but not both.

**If there is the possibility that there is preexisting production data that would not fit this constraint, a rake task should be included to clean this up**

Fixes #2742

### Deploy Notes
Since we define a group submission as being a `Submission` with a `group_id` but no `student_id`, and an individual `Submission` as being one with `student_id` but no `group_id`, we should make sure that there is no preexisting data that would violate this.

### Migrations
YES

### Steps to Test or Reproduce
- Verify that for any given student, one and only one `Submission` can be created on an individual assignment
- Verify that for any given group, one and only one `Submission` can be created on a group assignment
- Ensure that a `Submission` that is considered invalid cannot be created, e.g. it must have either a `group_id` or `student_id`, but not both

### CODE REVIEW

**Comment by jonathoy** [comment]
@chcholman Let me know if there is need for a rake task to ensure there is no bad `Submission` data.

File: app/models/submission.rb [hunk 1]
```diff
@@ -176,4 +177,8 @@ def cache_associations
     self.assignment_id ||= assignment.id
     self.course_id ||= assignment.course_id
   end
+
+  def student_xor_group
+    errors.add(:base, "must have either a student_id or group_id, but not both") unless student.nil? ^ group.nil?
```
Comment (acousticrobot) [inline app/models/submission.rb]: I think this is a great example of a well named definition that self-documents a somewhat obtuse logic gate.
