### PR TITLE
Final section rank

### LINKED ISSUE #4443: Sections: Section leaderboard ranks are not working properly
### Expected Behavior

Either the "rank" column would be based on the mean student score, or the section challenge score.

### Actual Behavior

It does not appear to be based on either of those. What it is based on is unclear.

### Steps to reproduce

This may require additional testing to narrow down what's happening. Generally, creating sections, section challenges and then grading those section challenges, and then observing what happens to the "rank" column on the sections page. Check out the screenshot below:

Screen Shot 2020-02-06 at 12 19 03 PM

A few observations:
There are two sections tied for "rank 1" - but they have different scores.
The section with the highest scores is ranked third. 
The two sections tied for "rank 1" are the two with the lowest scores.

### PR DESCRIPTION
**Pull request by dbrucknr**
### Status
**READY**

### Description
Fixes an issue where it wasn't clear how rank sequence was being calculated in the Section Leaderboards page. View linked issue

### Related PRs
List related PRs against other branches:

branch | PR
------ | ------
Correct section leaderboard rank | [4484]()

### Todos
- [x] Add Tests

### Migrations
YES

### Impacted Areas in Application
List general components of the application that this PR will affect:

* Section Leaderboard page at the /teams URL

======================
Closes #4443

### CODE REVIEW

File: app/models/course_membership.rb [hunk 1]
```diff
@@ -139,6 +139,8 @@ def student_team_score
   end
 
   def include_team_score?
+    # I THINK THIS FUNCTION IS RELATED TO THE RANKING OF SECTIONS/TEAMS
```
Comment (ebarroso7) [inline app/models/course_membership.rb:142]: Remove

File: app/models/team.rb [hunk 2]
```diff
@@ -70,38 +74,104 @@ def calculate_average_score
...
       team.update_attributes rank: rank
     end
   end
 
-  # Summing all of the points the team has earned across their challenges
-  def challenge_grade_score
-    # use student_visible scope from challenge_grades
-    challenge_grades.student_visible.sum("final_points") || 0
-  end
+    # Summing all of the points the team has earned across their challenges
```
Comment (ebarroso7) [inline app/models/team.rb:170]: Remove comment, remove extra spacing, and make the name of the method more readable like `challenge_grade_score_total`

File: db/migrate/20200511153619_change_teams_challenge_grade_score_default.rb [hunk 3]
```diff
@@ -0,0 +1,6 @@
+class ChangeTeamsChallengeGradeScoreDefault < ActiveRecord::Migration[5.2]
```
Comment (ebarroso7) [inline db/migrate/20200511153619_change_teams_challenge_grade_score_default.rb:1]: Nice! 👍

File: app/models/team.rb [hunk 4]
```diff
@@ -70,38 +74,104 @@ def calculate_average_score
...
+    end
+    return scored
+  end
+
+  def assign_highest_rank
+    teams_in_course = course.teams.count
+    self.update_attribute :rank, teams_in_course
+  end
+
+  def recalculate_rank_on_delete
```
Comment (ebarroso7) [inline app/models/team.rb:101]: I think there is some stuff we can refactor here, I haven't dug into it yet just noting it by size of method. Adding this review comment then looking more closely at this method
