### PR TITLE
3159 Add sample users file for download

### LINKED ISSUE #3159: Add Downloadable Sample File to import users page
### Expected Behavior
/users/import page should have a link to download a sample .csv file for submitting student roster import, similar to the "Download Sample File" link on the /assignments/:id/grades/importers/csv page. Downloaded file should only contain comma separated column names for the file.

### Actual Behavior
No such "Download Sample File" link exists on the /users/import page at this time.

### Steps to reproduce
N/A

### PR DESCRIPTION
**Pull request by dovek**
### Status
**IN DEVELOPMENT**

### Description
/users/import page should have a link to download a sample .csv file for submitting student roster import, similar to the "Download Sample File" link on the /assignments/:id/grades/importers/csv page. Downloaded file should only contain comma separated column names for the file.

### Related PRs
N/A

### Todos
- [x] Add Tests

### Deploy Notes
N/A

### Gem dependencies
N/A

### Migrations
NO

### Steps to Test or Reproduce
As an instructor, navigate to the "/users/import" page. Click the link for the sample file. Verify the format and data integrity of the downloaded file.

### Impacted Areas in Application
* Users Import

======================
Closes #3159

### CODE REVIEW

File: app/controllers/users/importers_controller.rb [hunk 1]
```diff
@@ -13,13 +13,25 @@ class Users::ImportersController < ApplicationController
       users_importer_users_path(params[:importer_provider_id], params[:id])
   end
   before_action :link_canvas_credentials, if: Proc.new { |c| c.params[:importer_provider_id] == "canvas" }
```
Comment (jonathoy) [inline app/controllers/users/importers_controller.rb]: You can probably add `except: :index` on this filter as well as the `do |controller|...` one, since they only pertain to situations where we are importing externally to an OAuth provider.

File: app/controllers/users/importers_controller.rb [hunk 2]
```diff
@@ -36,3 +48,25 @@ def users_import
     end
   end
 end
+
+private
+
+def generate_csv(options={})
```
Comment (jonathoy) [inline app/controllers/users/importers_controller.rb]: Just a suggestion, but an idea that you could do to keep this logic out of the controller is to move this into an exporter. You can see some of them in `app/exporters/`.

**Comment by jonathoy** [comment]
Looks good! Assigning to Cait for final review!
