### PR TITLE
Fix radio button grading for pass/fail assignments

### LINKED ISSUE #2956: Quick grade for pass/fail assignments gives wrong grading form
As an instructor, I have selected radio boxes as the setting for quick grade on  pass/fail assignments and i see a select box instead for each student

### PR DESCRIPTION
**Pull request by jonathoy**
### Status
READY

### Description
Previously if the quick grade style for an assignment was set as radio and the assignment was of pass/fail type, then the instructor would be presented with a select list. Radio buttons would only appear with this option if the assignment also had levels.

This is a quick fix for the bug mentioned in #2956 and not a PR that addresses the need for a larger usability refactor.

### Gem dependencies
N/A

### Migrations
NO

### Steps to Test or Reproduce

1. Set the quick grade styling for a Pass/Fail type assignment to radio buttons.
2. Ensure that grades persist on save and that there are radio buttons for when there are and are not assignment levels.

### Impacted Areas in Application
Assignment mass_edit

======================
Closes #2956

### CODE REVIEW

File: app/models/assignment.rb [hunk 1]
```diff
@@ -235,7 +235,11 @@ def grade_select?
   end
 
   def grade_radio?
-    mass_grade_type == "Radio Buttons" && has_levels?
+    if pass_fail?
```
Comment (chcholman) [inline app/models/assignment.rb]: I think this conditional can now be taken out, since we're handling this at the view level?

Comment (jonathoy) [inline app/models/assignment.rb]: Yep! Although as a side note when I reflect back on our decorator/presenter discussion, I wonder if these `mass_grade_type`-oriented methods might be better left off the model since they mainly deal with the views.

Comment (chcholman) [inline app/models/assignment.rb]: Totally agree with that direction
