### PR TITLE
3967 Google Batch Bug

### LINKED ISSUE #3967: Google::Apis::BatchError: Cannot make an empty batch request
View details in Rollbar: [https://rollbar.com/gradecraft/gradecraft-development/items/3277/](https://rollbar.com/gradecraft/gradecraft-development/items/3277/)

```

Google::Apis::BatchError: Cannot make an empty batch request
  File "/usr/local/bundle/gems/google-api-client-0.10.0/lib/google/apis/core/batch.rb", line 106, in prepare!
  File "/usr/local/bundle/gems/google-api-client-0.10.0/lib/google/apis/core/http_command.rb", line 94, in execute
  File "/usr/local/bundle/gems/google-api-client-0.10.0/lib/google/apis/core/base_service.rb", line 172, in batch
  File "/gradecraft/app/helpers/google_calendars_helper.rb", line 107, in add_batch_items
  File "/gradecraft/app/controllers/google_calendars/assignments_controller.rb", line 33, in add_assignments
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/basic_implicit_render.rb", line 4, in send_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb", line 188, in process_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb", line 30, in process_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb", line 20, in block in process_action
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 126, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 126, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 506, in block (2 levels) in compile
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 455, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 455, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 448, in block (2 levels) in around
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 267, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 267, in block (2 levels) in halting_and_conditional
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/core_ext/time/zones.rb", line 64, in use_zone
  File "/gradecraft/app/controllers/application_controller.rb", line 164, in time_zone
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 382, in block in make_lambda
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 266, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 266, in block in halting_and_conditional
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 447, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 447, in block in around
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 455, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 455, in call
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 101, in __run_callbacks__
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 750, in _run_process_action_callbacks
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb", line 90, in run_callbacks
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb", line 19, in process_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb", line 20, in process_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb", line 32, in block in process_action
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb", line 164, in block in instrument
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb", line 21, in instrument
  File "/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb", line 164, in instrument
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb", line 30, in process_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb", line 248, in process_action
  File "/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb", line 18, in process_action
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb", line 126, in process
  File "/usr/local/bundle/gems/actionview-5.0.0.1/lib/action_view/rendering.rb", line 30, in process
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb", line 190, in dispatch
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb", line 262, in dispatch
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb", line 50, in dispatch
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb", line 32, in serve
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb", line 39, in block in serve
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb", line 26, in each
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb", line 26, in serve
  File "/usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb", line 725, in call
  File "/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb", line 92, in call
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 190, in call!
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 168, in call
  File "/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb", line 92, in call
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 190, in call!
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 168, in call
  File "/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb", line 92, in call
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 190, in call!
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 168, in call
  File "/usr/local/bundle/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb", line 92, in call
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 190, in call!
  File "/usr/local/bundle/gems/omniauth-1.8.1/lib/omniauth/strategy.rb", line 168, in call
  File "/usr/l

### PR DESCRIPTION
**Pull request by dovek**
### Status
**IN DEVELOPMENT**

### Description
Current Behavior: In a course, it is possible for the "Add All Assignments" link button to appear while there are no assignments in the course. When a user clicks the button, there is a reported google error reporting that an empty batch cannot be processed.

Expected Behavior: The "Add All Assignments" link button should only appear if there are actually visible assignments in the course.

### Related PRs
N/A

### Todos
- [x] Add Tests

### Deploy Notes
N/A

### Gem dependencies
N/A

### Migrations
NO

### Steps to Test or Reproduce
NOTE: Before beginning, verify that the course you are testing in is an institutional course AND that the institution has opted to use Google Access.

As an instructor, in a course with no assignments, create 1 invisible assignment. On the instructor's Dashboard, the instructor should see the "Add All Assignments" link button. As a student, I should not see the "Add All Assignments" link button. As an instructor, edit the 1 assignment so that it is now visible. As a student I should now see the "Add All Assignments" link button.

### Impacted Areas in Application
List general components of the application that this PR will affect:

* Dashboards, Assignments

======================
Closes #3967

### CODE REVIEW

File: app/proctors/assignment_proctor.rb [hunk 1]
```diff
@@ -0,0 +1,13 @@
+class AssignmentProctor
+  attr_reader :assignment
+
+  def initialize(assignment)
+    @assignment = assignment
+  end
+
+  def viewable?(user, course)
+    return true if @assignment.visible?
+    return true if user.is_staff?(course) || user.is_admin?(course)
```
Comment (jonathoy) [inline app/proctors/assignment_proctor.rb]: A couple notes here:

1. `user.is_staff` technically covers if the user is an admin if you look at the `User` model.
2. I think that a better solution to this would be to check if `assignment.visible_for_student?`. There are conditions where if the assignment is locked and invisible that would not be accounted for if you just checked `assignment.visible?`.
3. I don't think that you need to pass the course in actually, because the visibility of the assignment will probably always be dependent on the course that the assignment is associated with.

That being said, if you wanted I think that you could simplify this method like so:

```
def viewable?(user)
  return true if user.is_staff?(@assignment.course)
  @assignment.visible_for_student?(user)
end
```

File: app/views/info/dashboard/modules/_dashboard_course_events.haml [hunk 2]
```diff
@@ -30,5 +30,5 @@
                   %li #{ link_to assignment.name, assignment } due at #{ l assignment.due_at.in_time_zone(current_user.time_zone) }
 
   .calendar-access
-    - if presenter.course.institution.try(:has_google_access)
+    - if presenter.course.institution.try(:has_google_access) && presenter.course.assignments.any? { |a| AssignmentProctor.new(a).viewable?(current_user, presenter.course) }
```
Comment (jonathoy) [inline app/views/info/dashboard/modules/_dashboard_course_events.haml]: We had mentioned that this was a little weird to put in the view and I think that the preferred thing to do here would be to take this line out and put it all in the presenter as some sort of `show_add_assignments_to_google_button?` method. This way it's also testable.

**Presenter**
```
def show_add_assignments_to_google_button?(user)
  course.institution.try(:has_google_access?) && course.assignments.any? { |a| AssignmentProctor.new(a).viewable?(user) }
end
```

**View**
```
- if presenter.show_add_assignments_to_google_button?(current_user)
```

File: spec/proctors/assignment_proctor_spec.rb [hunk 3]
```diff
@@ -0,0 +1,28 @@
+describe AssignmentProctor do
+  let(:assignment) { build_stubbed :assignment, course: course, visible: false }
+  let(:user) { build_stubbed :user }
+  let(:course) { build_stubbed :course }
+  let(:subject) { described_class.new assignment }
+
+  describe "#initialize" do
+    it "sets the given assignment to @assignment" do
+      expect(subject.instance_variable_get :@assignment).to eq assignment
```
Comment (jonathoy) [inline spec/proctors/assignment_proctor_spec.rb]: For the sake of trying to keep our test suite as slim as possible, I think that you can leave out this test. Realistically it should be pulled out of other proctor tests as well since we don't need to check that Rails constructors work properly.

**Comment by dovek** [comment]
@jonathoy Yes, I can confirm that we are filtering on the backend. There is a method called 'retrieve_visible_assignments' in the Google Calendars Helper that is filtering with assignment.visible_for_student?(current_user)
